Fixes
PashaKlybik/MultiSigWallet pull request #2
Opened 2018-07-13 10:38 UTC by altvnv

Added withdraw when creating multisig wallet, fixed internal transactions.

2018-07-13 14:52 UTC, Enmk commented
Ok

2018-07-17 11:27 UTC, PashaKlybik requested changes
Please fix before merging

2018-07-17 11:27 UTC, PashaKlybik commented on contracts/MultiSigWalletFactory.sol
> +    address public _owner;
Rename `_owner => _creator`

2018-07-17 12:14 UTC, PashaKlybik approved these changes
Good!

2018-07-17 12:15 UTC, merged